-- Plugin highlight groups

local M = {}

---@return table<string, vim.api.keyset.highlight>
function M.get()
  local p = require("synthwave-eightyfive.palette")
  local config = require("synthwave-eightyfive.config")
  local util = require("synthwave-eightyfive.util")

  local transparent = config.transparent
  local bg = transparent and p.none or p.bg
  local bg_float = transparent and p.none or p.bg_float

  return {
    -- Telescope
    TelescopeNormal = { fg = p.fg, bg = bg_float },
    TelescopeBorder = { fg = p.border, bg = bg_float },
    TelescopeTitle = { fg = p.pink, bold = true },
    TelescopePromptNormal = { fg = p.fg, bg = bg_float },
    TelescopePromptBorder = { fg = p.border, bg = bg_float },
    TelescopePromptTitle = { fg = p.pink, bold = true },
    TelescopePromptPrefix = { fg = p.orange },
    TelescopePromptCounter = { fg = p.comment },
    TelescopeResultsNormal = { fg = p.fg, bg = bg_float },
    TelescopeResultsBorder = { fg = p.border, bg = bg_float },
    TelescopeResultsTitle = { fg = p.pink, bold = true },
    TelescopePreviewNormal = { fg = p.fg, bg = bg_float },
    TelescopePreviewBorder = { fg = p.border, bg = bg_float },
    TelescopePreviewTitle = { fg = p.pink, bold = true },
    TelescopeSelection = { fg = p.fg, bg = p.bg_selection },
    TelescopeSelectionCaret = { fg = p.orange, bg = p.bg_selection },
    TelescopeMultiSelection = { fg = p.cyan, bg = p.bg_selection },
    TelescopeMultiIcon = { fg = p.cyan },
    TelescopeMatching = { fg = p.orange, bold = true },

    -- Neo-tree
    NeoTreeNormal = { fg = p.fg_muted, bg = bg },
    NeoTreeNormalNC = { fg = p.fg_muted, bg = bg },
    NeoTreeVertSplit = { fg = p.border, bg = bg },
    NeoTreeWinSeparator = { fg = p.border, bg = bg },
    NeoTreeEndOfBuffer = { fg = bg, bg = bg },
    NeoTreeRootName = { fg = p.pink, bold = true },
    NeoTreeGitAdded = { fg = p.git_add },
    NeoTreeGitDeleted = { fg = p.git_delete },
    NeoTreeGitModified = { fg = p.git_change },
    NeoTreeGitConflict = { fg = p.red, bold = true },
    NeoTreeGitUntracked = { fg = p.green },
    NeoTreeGitIgnored = { fg = p.git_ignored },
    NeoTreeIndentMarker = { fg = p.indent_guide },
    NeoTreeExpander = { fg = p.fg_muted },
    NeoTreeFileIcon = { fg = p.fg_muted },
    NeoTreeFileName = { fg = p.fg_muted },
    NeoTreeFileNameOpened = { fg = p.fg },
    NeoTreeDirectoryIcon = { fg = p.cyan },
    NeoTreeDirectoryName = { fg = p.cyan },
    NeoTreeSymbolicLinkTarget = { fg = p.pink },
    NeoTreeDotfile = { fg = p.comment },

    -- nvim-tree
    NvimTreeNormal = { fg = p.fg_muted, bg = bg },
    NvimTreeNormalNC = { fg = p.fg_muted, bg = bg },
    NvimTreeVertSplit = { fg = p.border, bg = bg },
    NvimTreeWinSeparator = { fg = p.border, bg = bg },
    NvimTreeEndOfBuffer = { fg = bg, bg = bg },
    NvimTreeRootFolder = { fg = p.pink, bold = true },
    NvimTreeGitDirty = { fg = p.git_change },
    NvimTreeGitNew = { fg = p.git_add },
    NvimTreeGitDeleted = { fg = p.git_delete },
    NvimTreeGitMerge = { fg = p.orange },
    NvimTreeGitRenamed = { fg = p.purple },
    NvimTreeGitStaged = { fg = p.green },
    NvimTreeGitIgnored = { fg = p.git_ignored },
    NvimTreeIndentMarker = { fg = p.indent_guide },
    NvimTreeFolderIcon = { fg = p.cyan },
    NvimTreeFolderName = { fg = p.cyan },
    NvimTreeOpenedFolderName = { fg = p.cyan, bold = true },
    NvimTreeEmptyFolderName = { fg = p.comment },
    NvimTreeSymlink = { fg = p.pink },
    NvimTreeSpecialFile = { fg = p.yellow },
    NvimTreeImageFile = { fg = p.purple },

    -- GitSigns
    GitSignsAdd = { fg = p.git_add },
    GitSignsChange = { fg = p.git_change },
    GitSignsDelete = { fg = p.git_delete },
    GitSignsAddNr = { fg = p.git_add },
    GitSignsChangeNr = { fg = p.git_change },
    GitSignsDeleteNr = { fg = p.git_delete },
    GitSignsAddLn = { bg = p.diff_add_bg },
    GitSignsChangeLn = { bg = util.blend(p.diff_change, p.bg, 0.2) },
    GitSignsDeleteLn = { bg = p.diff_delete_bg },
    GitSignsAddInline = { bg = p.diff_add_bg },
    GitSignsChangeInline = { bg = util.blend(p.diff_change, p.bg, 0.2) },
    GitSignsDeleteInline = { bg = p.diff_delete_bg },
    GitSignsCurrentLineBlame = { fg = p.comment },
    GitSignsAddPreview = { fg = p.git_add },
    GitSignsDeletePreview = { fg = p.git_delete },

    -- Gitsigns staged
    GitSignsStagedAdd = { fg = util.blend(p.git_add, p.bg, 0.5) },
    GitSignsStagedChange = { fg = util.blend(p.git_change, p.bg, 0.5) },
    GitSignsStagedDelete = { fg = util.blend(p.git_delete, p.bg, 0.5) },

    -- Indent Blankline
    IndentBlanklineChar = { fg = p.indent_guide, nocombine = true },
    IndentBlanklineSpaceChar = { fg = p.indent_guide, nocombine = true },
    IndentBlanklineSpaceCharBlankline = { fg = p.indent_guide, nocombine = true },
    IndentBlanklineContextChar = { fg = p.indent_guide_active, nocombine = true },
    IndentBlanklineContextStart = { sp = p.indent_guide_active, underline = true },
    IblIndent = { fg = p.indent_guide, nocombine = true },
    IblWhitespace = { fg = p.indent_guide, nocombine = true },
    IblScope = { fg = p.indent_guide_active, nocombine = true },

    -- Which-key
    WhichKey = { fg = p.cyan },
    WhichKeyGroup = { fg = p.pink },
    WhichKeyDesc = { fg = p.fg },
    WhichKeySeparator = { fg = p.comment },
    WhichKeyFloat = { bg = bg_float },
    WhichKeyBorder = { fg = p.border, bg = bg_float },
    WhichKeyValue = { fg = p.comment },

    -- Dashboard
    DashboardHeader = { fg = p.pink },
    DashboardCenter = { fg = p.cyan },
    DashboardFooter = { fg = p.comment },
    DashboardShortCut = { fg = p.yellow },

    -- Alpha
    AlphaHeader = { fg = p.pink },
    AlphaButtons = { fg = p.cyan },
    AlphaShortcut = { fg = p.yellow },
    AlphaFooter = { fg = p.comment },

    -- Lazy.nvim
    LazyButton = { fg = p.fg, bg = p.bg_popup },
    LazyButtonActive = { fg = p.fg, bg = p.bg_selection, bold = true },
    LazyComment = { fg = p.comment },
    LazyCommit = { fg = p.green },
    LazyCommitIssue = { fg = p.pink },
    LazyCommitType = { fg = p.cyan },
    LazyDimmed = { fg = p.comment },
    LazyDir = { fg = p.cyan },
    LazyH1 = { fg = p.bg, bg = p.pink, bold = true },
    LazyH2 = { fg = p.pink, bold = true },
    LazyNoCond = { fg = p.red },
    LazyNormal = { fg = p.fg, bg = bg_float },
    LazyProgressDone = { fg = p.pink },
    LazyProgressTodo = { fg = p.comment },
    LazyProp = { fg = p.comment },
    LazyReasonCmd = { fg = p.yellow },
    LazyReasonEvent = { fg = p.orange },
    LazyReasonFt = { fg = p.cyan },
    LazyReasonImport = { fg = p.green },
    LazyReasonKeys = { fg = p.pink },
    LazyReasonPlugin = { fg = p.purple },
    LazyReasonRuntime = { fg = p.fg_muted },
    LazyReasonSource = { fg = p.green },
    LazyReasonStart = { fg = p.yellow },
    LazySpecial = { fg = p.cyan },
    LazyTaskError = { fg = p.red },
    LazyTaskOutput = { fg = p.fg },
    LazyUrl = { fg = p.link, underline = true },
    LazyValue = { fg = p.green },

    -- Mason
    MasonHeader = { fg = p.bg, bg = p.pink, bold = true },
    MasonHeaderSecondary = { fg = p.bg, bg = p.cyan, bold = true },
    MasonHighlight = { fg = p.cyan },
    MasonHighlightBlock = { fg = p.bg, bg = p.cyan },
    MasonHighlightBlockBold = { fg = p.bg, bg = p.cyan, bold = true },
    MasonHighlightBlockBoldSecondary = { fg = p.bg, bg = p.pink, bold = true },
    MasonHighlightBlockSecondary = { fg = p.bg, bg = p.pink },
    MasonHighlightSecondary = { fg = p.pink },
    MasonMuted = { fg = p.comment },
    MasonMutedBlock = { fg = p.bg, bg = p.comment },
    MasonMutedBlockBold = { fg = p.bg, bg = p.comment, bold = true },
    MasonNormal = { fg = p.fg, bg = bg_float },

    -- Cmp (nvim-cmp)
    CmpItemAbbr = { fg = p.fg },
    CmpItemAbbrDeprecated = { fg = p.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.orange, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.orange, bold = true },
    CmpItemKind = { fg = p.pink },
    CmpItemKindClass = { fg = p.red },
    CmpItemKindColor = { fg = p.orange },
    CmpItemKindConstant = { fg = p.orange },
    CmpItemKindConstructor = { fg = p.red },
    CmpItemKindEnum = { fg = p.red },
    CmpItemKindEnumMember = { fg = p.orange },
    CmpItemKindEvent = { fg = p.pink },
    CmpItemKindField = { fg = p.pink },
    CmpItemKindFile = { fg = p.cyan },
    CmpItemKindFolder = { fg = p.cyan },
    CmpItemKindFunction = { fg = p.cyan },
    CmpItemKindInterface = { fg = p.red },
    CmpItemKindKeyword = { fg = p.yellow },
    CmpItemKindMethod = { fg = p.cyan },
    CmpItemKindModule = { fg = p.pink },
    CmpItemKindOperator = { fg = p.yellow },
    CmpItemKindProperty = { fg = p.pink },
    CmpItemKindReference = { fg = p.orange },
    CmpItemKindSnippet = { fg = p.green },
    CmpItemKindStruct = { fg = p.red },
    CmpItemKindText = { fg = p.fg },
    CmpItemKindTypeParameter = { fg = p.red },
    CmpItemKindUnit = { fg = p.orange },
    CmpItemKindValue = { fg = p.orange },
    CmpItemKindVariable = { fg = p.pink },
    CmpItemMenu = { fg = p.comment },

    -- Blink (blink.cmp)
    BlinkCmpLabel = { fg = p.fg },
    BlinkCmpLabelDeprecated = { fg = p.comment, strikethrough = true },
    BlinkCmpLabelMatch = { fg = p.orange, bold = true },
    BlinkCmpKind = { fg = p.pink },
    BlinkCmpKindClass = { fg = p.red },
    BlinkCmpKindColor = { fg = p.orange },
    BlinkCmpKindConstant = { fg = p.orange },
    BlinkCmpKindConstructor = { fg = p.red },
    BlinkCmpKindEnum = { fg = p.red },
    BlinkCmpKindEnumMember = { fg = p.orange },
    BlinkCmpKindEvent = { fg = p.pink },
    BlinkCmpKindField = { fg = p.pink },
    BlinkCmpKindFile = { fg = p.cyan },
    BlinkCmpKindFolder = { fg = p.cyan },
    BlinkCmpKindFunction = { fg = p.cyan },
    BlinkCmpKindInterface = { fg = p.red },
    BlinkCmpKindKeyword = { fg = p.yellow },
    BlinkCmpKindMethod = { fg = p.cyan },
    BlinkCmpKindModule = { fg = p.pink },
    BlinkCmpKindOperator = { fg = p.yellow },
    BlinkCmpKindProperty = { fg = p.pink },
    BlinkCmpKindReference = { fg = p.orange },
    BlinkCmpKindSnippet = { fg = p.green },
    BlinkCmpKindStruct = { fg = p.red },
    BlinkCmpKindText = { fg = p.fg },
    BlinkCmpKindTypeParameter = { fg = p.red },
    BlinkCmpKindUnit = { fg = p.orange },
    BlinkCmpKindValue = { fg = p.orange },
    BlinkCmpKindVariable = { fg = p.pink },
    BlinkCmpMenu = { fg = p.fg, bg = bg_float },
    BlinkCmpMenuBorder = { fg = p.border, bg = bg_float },
    BlinkCmpMenuSelection = { bg = p.bg_selection },
    BlinkCmpDoc = { fg = p.fg, bg = bg_float },
    BlinkCmpDocBorder = { fg = p.border, bg = bg_float },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = bg_float },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = bg_float },

    -- Notify
    NotifyERRORBorder = { fg = p.red },
    NotifyWARNBorder = { fg = p.yellow },
    NotifyINFOBorder = { fg = p.cyan },
    NotifyDEBUGBorder = { fg = p.comment },
    NotifyTRACEBorder = { fg = p.purple },
    NotifyERRORIcon = { fg = p.red },
    NotifyWARNIcon = { fg = p.yellow },
    NotifyINFOIcon = { fg = p.cyan },
    NotifyDEBUGIcon = { fg = p.comment },
    NotifyTRACEIcon = { fg = p.purple },
    NotifyERRORTitle = { fg = p.red },
    NotifyWARNTitle = { fg = p.yellow },
    NotifyINFOTitle = { fg = p.cyan },
    NotifyDEBUGTitle = { fg = p.comment },
    NotifyTRACETitle = { fg = p.purple },
    NotifyERRORBody = { fg = p.fg },
    NotifyWARNBody = { fg = p.fg },
    NotifyINFOBody = { fg = p.fg },
    NotifyDEBUGBody = { fg = p.fg },
    NotifyTRACEBody = { fg = p.fg },

    -- Noice
    NoiceCmdline = { fg = p.fg },
    NoiceCmdlineIcon = { fg = p.cyan },
    NoiceCmdlineIconSearch = { fg = p.yellow },
    NoiceCmdlinePopup = { fg = p.fg, bg = bg_float },
    NoiceCmdlinePopupBorder = { fg = p.border },
    NoiceCmdlinePopupTitle = { fg = p.pink },
    NoiceConfirm = { fg = p.fg, bg = bg_float },
    NoiceConfirmBorder = { fg = p.border },
    NoiceMini = { fg = p.fg, bg = bg },
    NoicePopup = { fg = p.fg, bg = bg_float },
    NoicePopupBorder = { fg = p.border },
    NoiceScrollbar = { bg = p.bg_popup },
    NoiceScrollbarThumb = { bg = p.fg_dimmed },

    -- Trouble
    TroubleNormal = { fg = p.fg, bg = bg },
    TroubleCount = { fg = p.pink, bg = p.bg_visual },
    TroubleText = { fg = p.fg },
    TroubleSource = { fg = p.comment },
    TroubleCode = { fg = p.comment },
    TroubleLocation = { fg = p.comment },
    TroubleIndent = { fg = p.indent_guide },
    TroubleFoldIcon = { fg = p.cyan },
    TroubleSignError = { fg = p.red },
    TroubleSignWarning = { fg = p.yellow },
    TroubleSignInformation = { fg = p.cyan },
    TroubleSignHint = { fg = p.green },

    -- Flash
    FlashBackdrop = { fg = p.comment },
    FlashMatch = { fg = p.fg, bg = util.blend(p.match, p.bg, 0.3) },
    FlashCurrent = { fg = p.fg, bg = util.blend(p.match, p.bg, 0.7) },
    FlashLabel = { fg = p.bg, bg = p.pink, bold = true },

    -- Leap
    LeapMatch = { fg = p.fg, bg = util.blend(p.match, p.bg, 0.7), bold = true },
    LeapLabelPrimary = { fg = p.bg, bg = p.pink, bold = true },
    LeapLabelSecondary = { fg = p.bg, bg = p.cyan, bold = true },
    LeapBackdrop = { fg = p.comment },

    -- Mini
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { bg = p.bg_visual },
    MiniCursorwordCurrent = { bg = p.bg_visual },
    MiniIndentscopeSymbol = { fg = p.indent_guide_active },
    MiniIndentscopePrefix = { nocombine = true },
    MiniJump = { fg = p.bg, bg = p.pink },
    MiniJump2dSpot = { fg = p.pink, bold = true },
    MiniStarterCurrent = {},
    MiniStarterFooter = { fg = p.comment, italic = true },
    MiniStarterHeader = { fg = p.pink },
    MiniStarterInactive = { fg = p.comment },
    MiniStarterItem = { fg = p.fg },
    MiniStarterItemBullet = { fg = p.border },
    MiniStarterItemPrefix = { fg = p.yellow },
    MiniStarterSection = { fg = p.cyan },
    MiniStarterQuery = { fg = p.orange },
    MiniStatuslineDevinfo = { fg = p.fg_muted, bg = p.bg_visual },
    MiniStatuslineFileinfo = { fg = p.fg_muted, bg = p.bg_visual },
    MiniStatuslineFilename = { fg = p.fg_muted, bg = p.bg_dark },
    MiniStatuslineInactive = { fg = p.comment, bg = p.bg_dark },
    MiniStatuslineModeCommand = { fg = p.bg, bg = p.yellow, bold = true },
    MiniStatuslineModeInsert = { fg = p.bg, bg = p.green, bold = true },
    MiniStatuslineModeNormal = { fg = p.bg, bg = p.cyan, bold = true },
    MiniStatuslineModeOther = { fg = p.bg, bg = p.purple, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg, bg = p.red, bold = true },
    MiniStatuslineModeVisual = { fg = p.bg, bg = p.pink, bold = true },
    MiniSurround = { fg = p.bg, bg = p.orange },
    MiniTablineCurrent = { fg = p.fg, bg = p.bg },
    MiniTablineFill = { bg = p.bg_dark },
    MiniTablineHidden = { fg = p.fg_muted, bg = p.bg_dark },
    MiniTablineModifiedCurrent = { fg = p.yellow, bg = p.bg },
    MiniTablineModifiedHidden = { fg = p.yellow, bg = p.bg_dark },
    MiniTablineModifiedVisible = { fg = p.yellow, bg = p.bg_dark },
    MiniTablineTabpagesection = { fg = p.fg, bg = p.bg_visual },
    MiniTablineVisible = { fg = p.fg_muted, bg = p.bg_dark },
    MiniTestEmphasis = { bold = true },
    MiniTestFail = { fg = p.red, bold = true },
    MiniTestPass = { fg = p.green, bold = true },
    MiniTrailspace = { bg = p.red },

    -- Nvim-navic
    NavicIconsFile = { fg = p.fg },
    NavicIconsModule = { fg = p.pink },
    NavicIconsNamespace = { fg = p.pink },
    NavicIconsPackage = { fg = p.pink },
    NavicIconsClass = { fg = p.red },
    NavicIconsMethod = { fg = p.cyan },
    NavicIconsProperty = { fg = p.pink },
    NavicIconsField = { fg = p.pink },
    NavicIconsConstructor = { fg = p.red },
    NavicIconsEnum = { fg = p.red },
    NavicIconsInterface = { fg = p.red },
    NavicIconsFunction = { fg = p.cyan },
    NavicIconsVariable = { fg = p.pink },
    NavicIconsConstant = { fg = p.orange },
    NavicIconsString = { fg = p.orange_bright },
    NavicIconsNumber = { fg = p.orange },
    NavicIconsBoolean = { fg = p.orange },
    NavicIconsArray = { fg = p.pink },
    NavicIconsObject = { fg = p.pink },
    NavicIconsKey = { fg = p.yellow },
    NavicIconsNull = { fg = p.orange },
    NavicIconsEnumMember = { fg = p.orange },
    NavicIconsStruct = { fg = p.red },
    NavicIconsEvent = { fg = p.pink },
    NavicIconsOperator = { fg = p.yellow },
    NavicIconsTypeParameter = { fg = p.red },
    NavicText = { fg = p.fg },
    NavicSeparator = { fg = p.comment },

    -- Bufferline
    BufferLineFill = { bg = p.bg_darker },
    BufferLineBackground = { fg = p.comment, bg = p.bg_dark },
    BufferLineBuffer = { fg = p.comment, bg = p.bg_dark },
    BufferLineBufferVisible = { fg = p.fg_muted, bg = p.bg },
    BufferLineBufferSelected = { fg = p.fg, bg = p.bg, bold = true },
    BufferLineTab = { fg = p.comment, bg = p.bg_dark },
    BufferLineTabSelected = { fg = p.pink, bg = p.bg, bold = true },
    BufferLineTabClose = { fg = p.red, bg = p.bg_dark },
    BufferLineTabSeparator = { fg = p.bg_darker, bg = p.bg_dark },
    BufferLineTabSeparatorSelected = { fg = p.bg_darker, bg = p.bg },
    BufferLineIndicatorSelected = { fg = p.pink, bg = p.bg },
    BufferLineIndicatorVisible = { fg = p.bg, bg = p.bg },
    BufferLineSeparator = { fg = p.bg_darker, bg = p.bg_dark },
    BufferLineSeparatorVisible = { fg = p.bg_darker, bg = p.bg },
    BufferLineSeparatorSelected = { fg = p.bg_darker, bg = p.bg },
    BufferLineCloseButton = { fg = p.comment, bg = p.bg_dark },
    BufferLineCloseButtonVisible = { fg = p.fg_muted, bg = p.bg },
    BufferLineCloseButtonSelected = { fg = p.red, bg = p.bg },
    BufferLineModified = { fg = p.yellow, bg = p.bg_dark },
    BufferLineModifiedVisible = { fg = p.yellow, bg = p.bg },
    BufferLineModifiedSelected = { fg = p.green, bg = p.bg },
    BufferLineDuplicate = { fg = p.comment, bg = p.bg_dark, italic = true },
    BufferLineDuplicateVisible = { fg = p.fg_muted, bg = p.bg, italic = true },
    BufferLineDuplicateSelected = { fg = p.fg_muted, bg = p.bg, italic = true },
    BufferLinePick = { fg = p.pink, bg = p.bg_dark, bold = true },
    BufferLinePickVisible = { fg = p.pink, bg = p.bg, bold = true },
    BufferLinePickSelected = { fg = p.pink, bg = p.bg, bold = true },
    BufferLineDiagnostic = { fg = p.comment, bg = p.bg_dark },
    BufferLineDiagnosticVisible = { fg = p.comment, bg = p.bg },
    BufferLineDiagnosticSelected = { fg = p.fg_muted, bg = p.bg },
    BufferLineError = { fg = p.red, bg = p.bg_dark },
    BufferLineErrorVisible = { fg = p.red, bg = p.bg },
    BufferLineErrorSelected = { fg = p.red, bg = p.bg },
    BufferLineErrorDiagnostic = { fg = p.red, bg = p.bg_dark },
    BufferLineErrorDiagnosticVisible = { fg = p.red, bg = p.bg },
    BufferLineErrorDiagnosticSelected = { fg = p.red, bg = p.bg },
    BufferLineWarning = { fg = p.yellow, bg = p.bg_dark },
    BufferLineWarningVisible = { fg = p.yellow, bg = p.bg },
    BufferLineWarningSelected = { fg = p.yellow, bg = p.bg },
    BufferLineWarningDiagnostic = { fg = p.yellow, bg = p.bg_dark },
    BufferLineWarningDiagnosticVisible = { fg = p.yellow, bg = p.bg },
    BufferLineWarningDiagnosticSelected = { fg = p.yellow, bg = p.bg },
    BufferLineInfo = { fg = p.cyan, bg = p.bg_dark },
    BufferLineInfoVisible = { fg = p.cyan, bg = p.bg },
    BufferLineInfoSelected = { fg = p.cyan, bg = p.bg },
    BufferLineInfoDiagnostic = { fg = p.cyan, bg = p.bg_dark },
    BufferLineInfoDiagnosticVisible = { fg = p.cyan, bg = p.bg },
    BufferLineInfoDiagnosticSelected = { fg = p.cyan, bg = p.bg },
    BufferLineHint = { fg = p.purple, bg = p.bg_dark },
    BufferLineHintVisible = { fg = p.purple, bg = p.bg },
    BufferLineHintSelected = { fg = p.purple, bg = p.bg },
    BufferLineHintDiagnostic = { fg = p.purple, bg = p.bg_dark },
    BufferLineHintDiagnosticVisible = { fg = p.purple, bg = p.bg },
    BufferLineHintDiagnosticSelected = { fg = p.purple, bg = p.bg },
    BufferLineNumbers = { fg = p.comment, bg = p.bg_dark },
    BufferLineNumbersVisible = { fg = p.fg_muted, bg = p.bg },
    BufferLineNumbersSelected = { fg = p.pink, bg = p.bg, bold = true },
    BufferLineGroupSeparator = { fg = p.comment, bg = p.bg_darker },
    BufferLineGroupLabel = { fg = p.bg, bg = p.pink, bold = true },
    BufferLineOffsetSeparator = { fg = p.border, bg = p.bg },
    BufferLineTruncMarker = { fg = p.comment, bg = p.bg_darker },
    -- DevIcon backgrounds (bufferline creates these dynamically for file icons)
    BufferLineDevIconDefault = { bg = p.bg_dark },
    BufferLineDevIconDefaultSelected = { bg = p.bg },
    BufferLineDevIconDefaultInactive = { bg = p.bg_dark },

    -- Lualine
    -- Note: Lualine has a dedicated theme at lua/lualine/themes/synthwave-eightyfive.lua
    -- Use: require("lualine").setup({ options = { theme = "synthwave-eightyfive" } })

    -- Snacks
    SnacksNormal = { fg = p.fg, bg = bg_float },
    SnacksDashboardNormal = { fg = p.fg, bg = bg },
    SnacksDashboardDesc = { fg = p.cyan },
    SnacksDashboardFile = { fg = p.fg_muted },
    SnacksDashboardDir = { fg = p.comment },
    SnacksDashboardFooter = { fg = p.comment },
    SnacksDashboardHeader = { fg = p.pink },
    SnacksDashboardIcon = { fg = p.cyan },
    SnacksDashboardKey = { fg = p.yellow },
    SnacksDashboardSpecial = { fg = p.pink },
    SnacksDashboardTitle = { fg = p.pink, bold = true },
    SnacksNotifierError = { fg = p.red },
    SnacksNotifierWarn = { fg = p.yellow },
    SnacksNotifierInfo = { fg = p.cyan },
    SnacksNotifierDebug = { fg = p.comment },
    SnacksNotifierTrace = { fg = p.purple },
    SnacksNotifierIconError = { fg = p.red },
    SnacksNotifierIconWarn = { fg = p.yellow },
    SnacksNotifierIconInfo = { fg = p.cyan },
    SnacksNotifierIconDebug = { fg = p.comment },
    SnacksNotifierIconTrace = { fg = p.purple },
    SnacksNotifierTitleError = { fg = p.red },
    SnacksNotifierTitleWarn = { fg = p.yellow },
    SnacksNotifierTitleInfo = { fg = p.cyan },
    SnacksNotifierTitleDebug = { fg = p.comment },
    SnacksNotifierTitleTrace = { fg = p.purple },
    SnacksNotifierBorderError = { fg = p.red },
    SnacksNotifierBorderWarn = { fg = p.yellow },
    SnacksNotifierBorderInfo = { fg = p.cyan },
    SnacksNotifierBorderDebug = { fg = p.comment },
    SnacksNotifierBorderTrace = { fg = p.purple },
    SnacksIndent = { fg = p.indent_guide },
    SnacksIndentScope = { fg = p.indent_guide_active },
  }
end

return M
